services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/pg_hba.conf
    environment:
      - POSTGRES_PASSWORD=theoa
      - POSTGRES_USER=theoa
      - POSTGRES_DB=fsdb
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - flightstrips
    restart: unless-stopped
    command: ["postgres"]

  flightstrip:
    build: .
    environment:
      - POSTGRES_USER=theoa
      - POSTGRES_PASSWORD=theoa
      - POSTGRES_DB=fsdb
      - SLEEP_TIME=30
    networks:
      - flightstrips
    restart: unless-stopped
    volumes:
      - ./localhost.crt:/myapp/bin/localhost.crt
      - ./localhost.key:/myapp/bin/localhost.key
    ports:
      - 2994:2994
    depends_on:
      postgres:
        condition: service_started

networks:
  flightstrips:

volumes:
  postgres:
