services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/pg_hba.conf
    environment:
      - POSTGRES_PASSWORD=theoa
      - POSTGRES_USER=theoa
      - POSTGRES_DB=fsdb
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - postgres-db-network
    restart: unless-stopped
    command: ["postgres"]

  flightstrip:
    build: .
    links:
      - postgres
    environment:
      - POSTGRES_USER=theoa
      - POSTGRES_PASSWORD=theoa
      - POSTGRES_DB=fsdb
      - SLEEP_TIME=30
    networks:
      - postgres-db-network
    restart: unless-stopped

networks:
  postgres-db-network:
    driver: bridge

volumes:
  postgres:
