positions:
  - name: "EKCH_DEL"
    frequency: "119.905"
  - name: "EKCH_A_GND"
    frequency: "121.630"
  - name: "EKCH_B_GND"
    frequency: "121.905"
  - name: "EKCH_C_GND"
    frequency: "121.730"
  - name: "EKCH_D_TWR"
    frequency: "119.355"
  - name: "EKCH_A_TWR"
    frequency: "118.105"
  - name: "EKCH_C_TWR"
    frequency: "118.580"
  - name: "EKCH_FMH"
    frequency: "120.500"
  - name: "EKCH_K_DEP"
    frequency: "124.980"
  - name: "EKCH_R_DEP"
    frequency: "120.255"
  - name: "EKCH_W_APP"
    frequency: "119.805"
  - name: "EKCH_O_APP"
    frequency: "118.455"
  - name: "EKCH_F_APP"
    frequency: "120.205"
  - name: "EKDK_V_CTR"
    frequency: "135.565"
  - name: "EKDK_L_CTR"
    frequency: "124.555"
  - name: "EKDK_N_CTR"
    frequency: "134.680"
  - name: "EKDK_UN_CTR"
    frequency: "136.555"
  - name: "EKDK_E_CTR"
    frequency: "123.730"
  - name: "EKDK_D_CTR"
    frequency: "133.155"
  - name: "EKDK_I_CTR"
    frequency: "121.380"
  - name: "EKDK_B_CTR"
    frequency: "119.555"
  - name: "EKDK_A_CTR"
    frequency: "135.290"
  - name: "EKDK_C_CTR"
    frequency: "128.215"
  - name: "EKDK_CTR"
    frequency: "136.485"
  - name: "EKDK_OE_CTR"
    frequency: "127.865"
  - name: "EKDK_WE_CTR"
    frequency: "126.055"


airborne_owners:
  - EKCH_W_APP
  - EKCH_O_APP
  - EKCH_R_DEP
  - EKCH_K_DEP
  - EKDK_I_CTR
  - EKDK_B_CTR
  - EKDK_E_CTR
  - EKDK_D_CTR
  - EKDK_OE_CTR
  - EKDK_WE_CTR
  - EKDK_CTR

airborne_routes:
  - name: K_DEP
    default: true
    sids:
      - BETUD2E
      - NEXEN2E
      - KOPEX2E
      - LANGO2E
      - KEMAX2E
      - SIMEG2E
      - SALLO1E
      - BETUD3B
      - NEXEN3B
      - KOPEX3B
      - LANGO3B
      - SIMEG9B
      - SALLO1B
      - BETUD2F
      - NEXEN2F
      - KOPEX2F
      - LANGO2F
      - KEMAX2F
      - SIMEG2F
      - SALLO1F
      - BETUD3D
      - NEXEN3D
      - KOPEX3D
      - LANGO3D
      - SIMEG9D
      - SALLO1D
      - BETUD2A
      - NEXEN2A
      - KOPEX2A
      - LANGO2A
      - KEMAX5A
      - SIMEG8A
      - SALLO1A
      - BETUD2C
      - NEXEN2C
      - KOPEX2C
      - LANGO2C
      - KEMAX5C
      - SIMEG9C
      - SALLO1C

  - name: R_DEP
    default: false
    sids:
      - ODDON1E
      - GOLGA3E
      - VEDAR3E
      - ODDON1B
      - GOLGA3B
      - VEDAR3B
      - KEMAX6B
      - ODDON1F
      - GOLGA2F
      - VEDAR2F
      - ODDON1D
      - GOLGA3D
      - VEDAR3D
      - KEMAX6D
      - ODDON1A
      - GOLGA3A
      - VEDAR4A
      - ODDON1C
      - GOLGA2C
      - VEDAR2C

sectors:
  - name: DEL
    name_priority: 10
    active: [ ]
    owner:
      - "EKCH_DEL"
      - "EKCH_A_GND"
      - "EKCH_B_GND"
      - "EKCH_C_TWR"
      - "EKCH_D_TWR"
      - "EKCH_A_TWR"
  - name: SQ
    name_priority: 0
    active: [ ]
    owner:
      - "EKCH_B_GND"

  # Apron
  - name: AA
    name_priority: 30
    region: APRON_NORTH
    active: [ ]
    constraints:
      departure: false
      arrival: true
    owner:
      - "EKCH_A_GND"
      - "EKCH_B_GND"
      - "EKCH_C_TWR"
      - "EKCH_D_TWR"
      - "EKCH_A_TWR"
  - name: AD
    name_priority: 20
    active: [ ]
    region: APRON_NORTH
    constraints:
      departure: true
      arrival: false
    owner:
      - "EKCH_C_GND"
      - "EKCH_B_GND"
      - "EKCH_A_GND"
      - "EKCH_C_TWR"
      - "EKCH_D_TWR"
      - "EKCH_A_TWR"
  - name: GW
    name_priority: 40
    active: [ ]
    region: GROUND_WEST
    owner:
      - "EKCH_C_TWR"
      - "EKCH_D_TWR"
      - "EKCH_A_TWR"

  # Towers 22s
  - name: TE
    name_priority: 50
    active: ["22L", "22R"]
    region: TOWER_EAST
    owner:
      - "EKCH_A_TWR"
      - "EKCH_D_TWR"
      - "EKCH_C_TWR"
  - name: TW
    name_priority: 50
    active: ["22L", "22R"]
    region: TOWER_WEST
    owner:
      - "EKCH_D_TWR"
      - "EKCH_A_TWR"
      - "EKCH_C_TWR"

  # Towers 04s
  - name: TE
    name_priority: 50
    active: ["04L", "04R"]
    region: TOWER_EAST
    owner:
      - "EKCH_D_TWR"
      - "EKCH_A_TWR"
      - "EKCH_C_TWR"
  - name: TW
    name_priority: 50
    active: ["04L", "04R"]
    region: TOWER_WEST
    owner:
      - "EKCH_A_TWR"
      - "EKCH_D_TWR"
      - "EKCH_C_TWR"

  # Airborne
  - name: K_DEP
    active: [ ]
    name_priority: 0
    owner:
      - EKCH_K_DEP
      - EKCH_R_DEP
      - EKCH_W_APP
      - EKCH_O_APP
      - EKDK_I_CTR
      - EKDK_B_CTR
      - EKDK_E_CTR
      - EKDK_D_CTR
      - EKDK_OE_CTR
      - EKDK_WE_CTR
      - EKDK_CTR

  - name: R_DEP
    active: [ ]
    name_priority: 0
    owner:
      - EKCH_R_DEP
      - EKCH_K_DEP
      - EKCH_W_APP
      - EKCH_O_APP
      - EKDK_I_CTR
      - EKDK_B_CTR
      - EKDK_E_CTR
      - EKDK_D_CTR
      - EKDK_OE_CTR
      - EKDK_WE_CTR
      - EKDK_CTR

routes:
  - name: Stands to Runway 22R
    forRunway: 22R
    active: [22R]
    path: [AD, GW, TW]
  - name: Stands to Runway 04R
    forRunway: 04R
    active: [04R]
    path: [AD, GW, TE]
  - name: Stands to Runway 22R cargo
    forRunway: 22R
    active: [22R]
    path: [TE, GW, TW]
  - name: Stands to Runway 04R cargo
    forRunway: 04R
    active: [04R]
    path: [TW]
  # TODO rest of the runways
  - name: Runway 22L/04R to high A stands
    forStandRanges:
      - A17-A33
      - A4
      - A6
      - A8
    active: [22L, 04R]
    path: [TE, GW, AA]
  - name: Runway 22L/04R to cargo
    forStandRanges:
      - G110-G137
    active: [22L, 04R]
    path: [TE]
  - name: Runway 22L to rest
    forStandRanges:
      - A7
      - A9-A15
      - B3-B19
      - C10-C27
      - D1-D4
      - E20-E90
      - F1-F99
      - H101-H106
    active: [22L, 04R]
    path: [TE, AA]
  - name: Runway 04L/22R to high A stands
    forStandRanges:
      - A17-A33
      - A4
      - A6
      - A8
    active: [04L, 22R]
    path: [TW, GW, AA]
  - name: Runway 04L/22R to cargo
    forStandRanges:
      - G110-G137
    active: [04L, 22R]
    path: [TW, GW, TE]
  - name: Runway 04L/22R to rest
    forStandRanges:
      - A7
      - A9-A15
      - B3-B19
      - C10-C27
      - D1-D4
      - E20-E90
      - F1-F99
      - H101-H106
    active: [04L, 22R]
    path: [TW, GW, AA]
