version: "3"
services:
  db:
    image: docker.io/library/mariadb:11
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: flightstrips
      MARIADB_ROOT_PASSWORD: root
    networks:
      - flightstrips
    volumes:
      - data:/var/lib/mysql
    profiles:
      - services
      - all
  host:
    image: ghcr.io/frederikrosenberg/flightstrips/host:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.Host
    ports:
      - 5233:8080
    restart: on-failure
    environment:
      ConnectionStrings__Database: "Server=db;Port=3306;Database=flightstrips;Uid=root;Pwd=root"
    networks:
      - flightstrips
    profiles:
      - all
    depends_on:
      db:
        condition: service_started

volumes:
  data:

networks:
  flightstrips:
