version: "3"
services:
  db:
    image: postgres:16
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - flightstrips
    volumes:
      - data:/var/lib/postgresql/data/
    profiles:
      - services
      - all
  host:
    image: ghcr.io/frederikrosenberg/flightstrips/host:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.Host
    ports:
      - 5233:8080
    restart: on-failure
    environment:
      ConnectionStrings__Database: "Host=db;Port=5432;Database=flightstrips; Username=postgres; Password=password"
    networks:
      - flightstrips
    profiles:
      - all
    depends_on:
      db:
        condition: service_started

volumes:
  data:

networks:
  flightstrips:
