version: '3'
services:
  db:
    image: docker.io/library/mariadb:11
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: flightstrips
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - data:/var/lib/mysql

volumes:
  data: