services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/database
      - ./pg_hba.conf:/var/lib/postgresql/pg_hba.conf
    environment:
      - POSTGRES_PASSWORD=fs_password
      - POSTGRES_USER=fs
      - POSTGRES_DB=fsdb
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - flightstrips
    restart: unless-stopped
    command: ["postgres"]
    profiles: [all, database]

  flightstrip:
    build: .
    environment:
      - DATABASE_CONNECTIONSTRING=postgresql://fs:fs_password@postgres:5432/fsdb?sslmode=disable
      - SLEEP_TIME=30
    networks:
      - flightstrips
    restart: unless-stopped
    ports:
      - 2994:2994
    depends_on:
      postgres:
        condition: service_started
    profiles: [all]

networks:
  flightstrips:

volumes:
  postgres:
